name: Create Release from Tags and push Artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
          uses: thatisuday/go-cross-build@v1
          with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'cmd/...'
            name: 'update-tag'
            compress: 'false'
            dest: 'dist'
      - name: Upload build-artifacts
          uses: skx/github-action-publish-binaries@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: "./dist/*"
